### ISSUE TITLE
make boot, QEMU hangs at "Booting from ROM..."

### ISSUE THREAD

**Issue by resinbeard** [linux-kernel-labs/linux-kernel-labs.github.io#24]
make boot, QEMU hangs at "Booting from ROM..."

`mfoster@cyperus ~/Dev/linux-kernel-labs/tools/labs $ sudo modprobe tun
`

`mfoster@cyperus ~/Dev/linux-kernel-labs/tools/labs $ QEMU_DISPLAY=sdl make boot
qemu/create_net.sh tap0
qemu/create_net.sh tap1
/home/mfoster/Dev/linux-kernel-labs/tools/labs/templates/assignments/6-e100/nttcp -v -i &
nttcp-l: nttcp, version 1.47
nttcp-l: running in inetd mode on port 5037 - ignoring options beside -v and -p
ARCH=x86 qemu/qemu.sh -kernel /home/mfoster/Dev/linux-kernel-labs/arch/x86/boot/bzImage -device virtio-serial -chardev pty,id=virtiocon0 -device virtconsole,chardev=virtiocon0 -serial pipe:pipe1 -serial pipe:pipe2 -netdev tap,id=tap0,ifname=tap0,script=no,downscript=no -net nic,netdev=tap0,model=virtio -netdev tap,id=tap1,ifname=tap1,script=no,downscript=no -net nic,netdev=tap1,model=i82559er -drive file=core-image-minimal-qemux86.ext4,if=virtio,format=raw -drive file=disk1.img,if=virtio,format=raw -drive file=disk2.img,if=virtio,format=raw --append "root=/dev/vda loglevel=15 console=hvc0" --display sdl -s -m 256
char device redirected to /dev/pts/2 (label virtiocon0)
`

`mfoster@cyperus ~/Dev/linux-kernel-labs/tools/labs $ uname -a
Linux cyperus 5.4.97-gentoo #1 SMP PREEMPT Sat Feb 20 21:21:41 PST 2021 x86_64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz GenuineIntel GNU/Linux
`

`mfoster@cyperus ~/Dev/linux-kernel-labs/tools/labs $ gcc --version
gcc (Gentoo 9.3.0-r2 p4) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
`

`mfoster@cyperus ~/Dev/linux-kernel-labs/tools/labs $ find /lib -iname 'libc*.so'
/lib/libcrypt-2.32.so
/lib/libc-2.32.so
`

**Comment by dbaluta** [comment]
@resinbeard what is your last commit in the linux-kernel-labs tree. We switched to 5.10 recently. Did this ever worked on your machine?

**Comment by walac** [comment]
I am having the same problem with commit `fac865c0d50c6e62272f4c00e19f23a22e7587d7`

**Comment by dbaluta** [comment]
Maybe this?   https://stackoverflow.com/questions/60136854/qemu-hangs-at-boot-time

It's hard to debug this problem remotely.

**Comment by dbaluta** [comment]
Ok, I think the error comes from the fact that our scripts built the kernel for x86_64 but when it tries to run it on a 32 bit CPU. Not sure why this happens.

I've know started a rebuild with:
```
$ cd tools/labs/
$ DISPLAY=gtk ARCH=i386 make boot
```

I will post tomorrow about results as it is very late on my side.

**Comment by dbaluta** [comment]
Dismiss my last comment. One of the problem should be fixed with:

https://github.com/linux-kernel-labs/linux/pull/227

Then running `make boot` should just work.

**Comment by resinbeard** [comment]
@dbaluta this hasn't worked before, but yesterday was my first attempt.
my last commit is `fac865c0d50c6e62272f4c00e19f23a22e7587d7`, i'll try the changes in PR linux-kernel-labs/linux#227

**Comment by resinbeard** [comment]
i've run into the same problem at first ("Booting from ROM..."), but then i tried commenting-out one or all of the serial-related qemu args in tools/labs/qemu/Makefile, specifically these:
```
        -device virtio-serial \
        -chardev pty,id=virtiocon0 -device virtconsole,chardev=virtiocon0 \
        -serial pipe:pipe1 -serial pipe:pipe2 \
```
i am now at the point where I hit a kernel panic booting the kernel. i've uncommented all of the args and am still receiving the kernel panic so perhaps i unstuck something on the initial boot?
my next step is to get more info about what's being borked using Kexec

**Comment by dbaluta** [comment]
Please update the tree now and also apply this PR: https://github.com/linux-kernel-labs/linux/pull/228

Then it should work fine.

**Comment by dbaluta** [comment]
@resinbeard  @walac all PR are now merged. Can you please update and notify us if it is working now, so we can close this issue?

**Comment by walac** [comment]
@dbaluta I had to follow the steps below and it worked:

* Update my branch
* `make olddefconfig`
* `make savedefconfig`
* `make menuconfig`
* Uncheck the "64 bit kernel" option
* `make all`
* `cd tools/labs`
* `make boot`
* Success \o/

Thanks a lot!

**Comment by dbaluta** [comment]
If you use `ARCH=x86` there should be no need for unchecking the `64 bit kernel option`.
